# this runs key services for WorkRail application: PostgreSQL and pgAdmin
services:
  db:
    image: postgres:16
    container_name: workrail-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: workrail
      POSTGRES_PASSWORD: workrail_password
      POSTGRES_DB: workrail_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: workrail-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: workrail@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  garage:
    image: dxflrs/garage:v2.1.0
    container_name: workrail-garage
    hostname: garage
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
    ports:
      - "3900:3900" # S3 API
      - "3901:3901" # RPC
      - "3903:3903" # Admin API

  garage_webui:
    image: khairul169/garage-webui:latest
    container_name: workrail-garage-webui
    restart: unless-stopped
    depends_on:
      - garage
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
    ports:
      - "3909:3909"
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"

volumes:
  db_data:
  pgadmin_data:
  garage_meta:
  garage_data:
